var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/kategorie/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01kp_ym._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tmbvij._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0p7uxji.js")
R.c("server/chunks/ssr/[root-of-the-server]__005-a9y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p6raf8._.js")
R.c("server/chunks/ssr/_12b1u4r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_kategorie_[slug]_page_actions_11xu6qc.js")
R.m(8229)
module.exports=R.m(8229).exports
