#!/usr/bin/env python3
"""Pull current Cognitor CMS data into ./cms-data.js for the React app.

Usage: python3 scripts/build_data.py

Run after CMS edits to refresh the static snapshot. This exists because the
Cognitor public endpoint only allow-lists `app.cognitor.dev` for CORS, so
direct browser fetch from any other origin is blocked.
"""
import os, sys, json, requests, urllib3
from pathlib import Path

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

ROOT = Path(__file__).resolve().parent.parent
ENV = {}
for line in (ROOT / '.env').read_text().splitlines():
    if '=' in line and not line.strip().startswith('#'):
        k, v = line.split('=', 1)
        ENV[k.strip()] = v.strip()

BASE = ENV['BASEURL']
SITE = ENV['SITE']
TYPES = ['category', 'tool', 'article', 'recent-change']

def fetch(type_key):
    url = f'{BASE}/public/{SITE}/elements/?type={SITE}_{type_key}&limit=500'
    r = requests.get(url, verify=False, timeout=30)
    r.raise_for_status()
    items = r.json()
    return [{**el['data'], '_id': el['id'], '_updated': el['updated_at']} for el in items]

print(f'Fetching from {BASE}/public/{SITE}/elements/ ...')
data = {
    'categories':    sorted(fetch('category'),      key=lambda x: x.get('order', 999)),
    'tools':         fetch('tool'),
    'articles':      fetch('article'),
    'recentChanges': sorted(fetch('recent-change'), key=lambda x: x.get('order', 999)),
}
for k, v in data.items():
    print(f'  · {k}: {len(v)}')

out = ROOT / 'cms-data.js'
out.write_text(
    '// Auto-generated by scripts/build_data.py — do not edit by hand.\n'
    '// Source: Cognitor CMS (' + BASE + '/public/' + SITE + '/elements/)\n'
    'window.KI_DATA = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n',
    encoding='utf-8',
)
print(f'\n✓ Wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)')
