#!/bin/bash
# Deterministic tail of the weekly auto-discovery pipeline.
# Assumes scripts/pending_tools.json has already been written (by the
# weekly-tool-discovery workflow). No-ops safely if there is nothing to do.
#
# Steps: seed → screenshot capture → upload → cover generation → Netlify
# deploy → git commit + push. Idempotent throughout.
#
# Usage:  bash scripts/weekly_discovery_run.sh
# Exit:   0 = success or nothing-to-do, non-zero = a step failed.

set -uo pipefail

REPO="/Users/astoeckl/Documents/tool navigator"
cd "$REPO" || { echo "✗ repo not found: $REPO"; exit 1; }

# Make sure the common toolchain is on PATH (launchd runs with a minimal env).
export PATH="/opt/homebrew/bin:/opt/homebrew/opt/python@3.13/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

PENDING="scripts/pending_tools.json"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ---- 0. Anything to do? ----
if [ ! -s "$PENDING" ]; then
  log "No pending_tools.json — nothing to add this week. Done."
  exit 0
fi
COUNT=$(python3 -c "import json,sys; print(len(json.load(open('$PENDING'))))" 2>/dev/null || echo 0)
if [ "$COUNT" = "0" ]; then
  log "pending_tools.json is empty — nothing to add. Done."
  rm -f "$PENDING"
  exit 0
fi
log "Found $COUNT candidate tool(s) to add."

# ---- 1. Seed elements + posts + logos, register capture/cover entries ----
log "Seeding into CMS …"
SEED_OUT=$(python3 scripts/seed_pending_tools.py 2>&1)
echo "$SEED_OUT"
ADDED=$(echo "$SEED_OUT" | grep '^ADDED_SLUGS=' | cut -d= -f2)
if [ -z "$ADDED" ]; then
  log "Seeder added 0 new tools (all duplicates?). Nothing further to do."
  exit 0
fi
log "Newly added slugs: $ADDED"

# ---- 2. Capture website screenshots ----
log "Capturing screenshots …"
cp scripts/capture_tool_screenshots.mjs web/capture_tmp.mjs
( cd web && node capture_tmp.mjs ) || log "⚠ capture reported issues (continuing)"
rm -f web/capture_tmp.mjs

# ---- 3. Upload screenshots ----
log "Uploading screenshots …"
python3 scripts/upload_screenshots.py || { log "✗ upload_screenshots failed"; exit 1; }

# ---- 4. Generate cover images ----
log "Generating cover images …"
python3 scripts/generate_tool_images.py || { log "✗ generate_tool_images failed"; exit 1; }

# ---- 5. Deploy to Netlify ----
log "Deploying to Netlify …"
set -a; source .env 2>/dev/null; set +a   # loads NETLIFY_AUTH_TOKEN
( cd web && ./node_modules/.bin/netlify deploy --build --prod ) || { log "✗ Netlify deploy failed"; exit 1; }

# ---- 6. Commit + push ----
log "Committing + pushing …"
git add scripts/capture_tool_screenshots.mjs scripts/generate_tool_images.py scripts/pending_archive 2>/dev/null
COMMIT_MSG="Weekly auto-discovery: add tools ($ADDED)

Generated by the weekly-tool-discovery workflow + weekly_discovery_run.sh.

Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>"
git commit -m "$COMMIT_MSG" || log "⚠ nothing to commit"
git push || { log "✗ git push failed"; exit 1; }

log "✓ Weekly discovery complete. Added: $ADDED"
