var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/tool/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0udrwqg._.js")
R.c("server/chunks/ssr/_0ze_yt9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0r8wuib.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tmbvij._.js")
R.c("server/chunks/ssr/[root-of-the-server]__005-a9y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p6raf8._.js")
R.c("server/chunks/ssr/_12b1u4r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_tool_[slug]_page_actions_0df~h4u.js")
R.m(21242)
module.exports=R.m(21242).exports
